package edu.hm.cs.jenkins.web.security;

/**
 * Encapsulates the data which is needed for the authentication.
 *
 * @author Tobias Wochinger
 */
public class Authentication {

    private final String username;

    private final String token;

    /**
     * Creates an authentication which provides the needed data.
     *
     * @param username name of the user who wants to access Jenkins
     *                 and who is owner of the token
     * @param token    token of the user generated by Jenkins
     */
    public Authentication(final String username, final String token) {
        this.username = username;
        this.token = token;
    }

    public String getUsername() {
        return username;
    }

    public String getToken() {
        return token;
    }
}
